// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - TanStack devtools (dev-only, first), tanstackStart, viteReact, tailwindcss, tsConfigPaths,
//     nitro (build-only using cloudflare as a default target), VITE_* env injection, @ path alias,
//     React/TanStack dedupe, error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

/**
 * Lovable's Nitro build emits a Cloudflare worker at `.output/server/index.mjs`,
 * while TanStack Start's `vite preview` middleware imports
 * `dist/server/server.js`. Keep a tiny adapter in the build output so the
 * production preview exercises the same worker bundle that is deployed.
 */
function productionPreviewShim() {
  return {
    name: "wifiguard-production-preview-shim",
    apply: "build" as const,
    buildApp: {
      order: "post" as const,
      async handler() {
        const root = process.cwd();
        const targetDir = resolve(root, "dist/server");
        const wranglerPath = resolve(root, ".output/server/wrangler.json");
        let vars: Record<string, unknown> = {};

        try {
          const parsed = JSON.parse(await readFile(wranglerPath, "utf8"));
          if (parsed.vars && typeof parsed.vars === "object" && !Array.isArray(parsed.vars)) {
            vars = parsed.vars;
          }
        } catch {
          // A local preview does not require Cloudflare vars; VITE_* values are bundled.
        }

        await mkdir(targetDir, { recursive: true });
        await writeFile(
          resolve(targetDir, "server.js"),
          `// Generated by WiFiGuard for TanStack Start's vite preview.\n` +
            `import { readFile } from "node:fs/promises";\n` +
            `import { extname } from "node:path";\n` +
            `import worker from "../../.output/server/index.mjs";\n\n` +
            `const publicRoot = new URL("../../.output/public/", import.meta.url);\n` +
            `const contentTypes = { ".css": "text/css; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".mjs": "text/javascript; charset=utf-8", ".json": "application/json; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png", ".ico": "image/x-icon", ".woff": "font/woff", ".woff2": "font/woff2" };\n` +
            `const assets = { async fetch(request) {\n` +
            `  const pathname = decodeURIComponent(new URL(request.url).pathname).replace(/^\\/+/, "");\n` +
            `  const file = new URL(pathname, publicRoot);\n` +
            `  if (!file.href.startsWith(publicRoot.href)) return new Response("Not found", { status: 404 });\n` +
            `  try {\n` +
            `    const body = await readFile(file);\n` +
            `    return new Response(body, { headers: { "content-type": contentTypes[extname(pathname)] || "application/octet-stream" } });\n` +
            `  } catch {\n` +
            `    return new Response("Not found", { status: 404 });\n` +
            `  }\n` +
            `} };\n` +
            `const env = { ...${JSON.stringify(vars)}, ASSETS: assets };\n` +
            `const ctx = { waitUntil() {}, passThroughOnException() {}, props: {} };\n\n` +
            `export default {\n` +
            `  fetch(request) {\n` +
            `    Object.defineProperty(request, "ip", { value: undefined, writable: true, configurable: true });\n` +
            `    return worker.fetch(request, env, ctx);\n` +
            `  },\n` +
            `};\n`,
          "utf8",
        );
      },
    },
  };
}

export default defineConfig({
  plugins: [productionPreviewShim()],
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
  },
});
