"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-07 11:31:37.036656+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('invite_code', sa.Text(), nullable=False),
    sa.Column('root_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("invite_code ~ '^[A-Z]{2,3}-[0-9]{4}$'", name=op.f('ck_facilities_invite_code_format')),
    # root_user_id -> users.id 는 순환 FK: users 생성 후 아래에서 ALTER 로 추가한다 (DEFERRABLE INITIALLY DEFERRED).
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities')),
    sa.UniqueConstraint('invite_code', name=op.f('uq_facilities_invite_code'))
    )
    op.create_table('presence_samples',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('mv_current', sa.Float(), nullable=True),
    sa.Column('wander_current', sa.Float(), nullable=True),
    sa.Column('mv_threshold', sa.Float(), nullable=True),
    sa.Column('wander_baseline', sa.Float(), nullable=True),
    sa.Column('wander_ratio_threshold', sa.Float(), nullable=True),
    sa.Column('wander_ratio', sa.Float(), nullable=True),
    sa.Column('wander_confirmed', sa.Boolean(), nullable=True),
    sa.Column('last_activity_at', sa.Float(), nullable=True),
    sa.Column('seconds_since_activity', sa.Float(), nullable=True),
    sa.Column('just_changed', sa.Boolean(), nullable=True)
    )
    op.create_index('presence_samples_device_ts', 'presence_samples', ['facility_id', 'device_id', 'ts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('onboarded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(service = 'HOME' AND role = 'USER' AND facility_id IS NULL) OR (service = 'FACILITY' AND role IN ('ROOT','MEMBER') AND facility_id IS NOT NULL)", name=op.f('ck_users_service_role')),
    sa.CheckConstraint("role IN ('ROOT','MEMBER','USER')", name=op.f('ck_users_role')),
    sa.CheckConstraint("service IN ('HOME','FACILITY')", name=op.f('ck_users_service')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_users_facility_id_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ux_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_foreign_key(
        'fk_facilities_root_user_id_users', 'facilities', 'users', ['root_user_id'], ['id'],
        deferrable=True, initially='DEFERRED',
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('room', sa.Text(), nullable=False),
    sa.Column('connection', sa.Text(), nullable=False),
    sa.Column('mqtt_topic', sa.Text(), nullable=True),
    sa.Column('serial_port', sa.Text(), nullable=True),
    sa.Column('mac', sa.Text(), nullable=True),
    sa.Column('fw', sa.Text(), nullable=True),
    sa.Column('online', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_rssi', sa.Float(), nullable=True),
    sa.Column('current_rssi', sa.Float(), nullable=True),
    sa.Column('agc', sa.Float(), nullable=True),
    sa.Column('noise_floor', sa.Float(), nullable=True),
    sa.Column('calibrating', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('calibration_stage', sa.Text(), server_default=sa.text("'IDLE'"), nullable=False),
    sa.Column('calibration_progress', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('presence_mv_threshold', sa.Float(), nullable=True),
    sa.Column('wander_baseline', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("(connection = 'MQTT' AND mqtt_topic IS NOT NULL) OR (connection = 'SERIAL' AND serial_port IS NOT NULL)", name=op.f('ck_devices_connection_target')),
    sa.CheckConstraint("calibration_stage IN ('IDLE','LEAVING','WAITING_ACK','WAITING_AGC','MEASURING','DONE','ERROR')", name=op.f('ck_devices_calibration_stage')),
    sa.CheckConstraint("connection IN ('MQTT','SERIAL')", name=op.f('ck_devices_connection')),
    sa.CheckConstraint('(facility_id IS NOT NULL) <> (owner_user_id IS NOT NULL)', name=op.f('ck_devices_scope_xor')),
    sa.CheckConstraint('calibration_progress >= 0 AND calibration_progress <= 1', name=op.f('ck_devices_calibration_progress_range')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_devices_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_devices_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_facility_id'), 'devices', ['facility_id'], unique=False)
    op.create_index(op.f('ix_devices_owner_user_id'), 'devices', ['owner_user_id'], unique=False)
    op.create_index('ux_devices_scope_topic', 'devices', [sa.literal_column('COALESCE(facility_id, owner_user_id)'), 'mqtt_topic'], unique=True, postgresql_where=sa.text('mqtt_topic IS NOT NULL'))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('residents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('room', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('caregiver', sa.Text(), nullable=True),
    sa.Column('threshold_override', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('(facility_id IS NOT NULL) <> (owner_user_id IS NOT NULL)', name=op.f('ck_residents_scope_xor')),
    sa.CheckConstraint('age IS NULL OR (age >= 0 AND age <= 150)', name=op.f('ck_residents_age_range')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_residents_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_residents_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_residents'))
    )
    op.create_index(op.f('ix_residents_facility_id'), 'residents', ['facility_id'], unique=False)
    op.create_index(op.f('ix_residents_owner_user_id'), 'residents', ['owner_user_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('presence_mv_threshold', sa.Float(), server_default=sa.text('2.0'), nullable=False),
    sa.Column('wander_ratio_threshold', sa.Float(), server_default=sa.text('1.8'), nullable=False),
    sa.Column('presence_timeout_s', sa.Float(), server_default=sa.text('10.0'), nullable=False),
    sa.Column('threshold', sa.Float(), server_default=sa.text('0.468'), nullable=False),
    sa.Column('cooldown_seconds', sa.Float(), server_default=sa.text('10.0'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(facility_id IS NOT NULL) <> (owner_user_id IS NOT NULL)', name=op.f('ck_tenant_configs_scope_xor')),
    sa.CheckConstraint('cooldown_seconds >= 0', name=op.f('ck_tenant_configs_cooldown_nonneg')),
    sa.CheckConstraint('presence_mv_threshold > 0', name=op.f('ck_tenant_configs_mv_threshold_positive')),
    sa.CheckConstraint('presence_timeout_s > 0', name=op.f('ck_tenant_configs_timeout_positive')),
    sa.CheckConstraint('threshold >= 0 AND threshold <= 1', name=op.f('ck_tenant_configs_threshold_range')),
    sa.CheckConstraint('wander_ratio_threshold >= 1.0', name=op.f('ck_tenant_configs_wander_ratio_min')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_tenant_configs_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_tenant_configs_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_tenant_configs_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_configs')),
    sa.UniqueConstraint('facility_id', name=op.f('uq_tenant_configs_facility_id')),
    sa.UniqueConstraint('owner_user_id', name=op.f('uq_tenant_configs_owner_user_id'))
    )
    op.create_table('fall_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('resident_name', sa.Text(), nullable=False),
    sa.Column('room', sa.Text(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'SIMULATED'"), nullable=False),
    sa.Column('response', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('responded_by', sa.UUID(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("response IN ('PENDING','ACKNOWLEDGED','DISPATCHED','FALSE_ALARM')", name=op.f('ck_fall_events_response')),
    sa.CheckConstraint("source IN ('EDGE','SIMULATED','SEED')", name=op.f('ck_fall_events_source')),
    sa.CheckConstraint('(facility_id IS NOT NULL) <> (owner_user_id IS NOT NULL)', name=op.f('ck_fall_events_scope_xor')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_fall_events_confidence_range')),
    sa.CheckConstraint('duration_s >= 0', name=op.f('ck_fall_events_duration_nonneg')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_fall_events_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_fall_events_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_fall_events_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], name=op.f('fk_fall_events_resident_id_residents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], name=op.f('fk_fall_events_responded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fall_events'))
    )
    op.create_index(op.f('ix_fall_events_facility_id'), 'fall_events', ['facility_id'], unique=False)
    op.create_index('ix_fall_events_facility_ts', 'fall_events', ['facility_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('ix_fall_events_owner_ts', 'fall_events', ['owner_user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('ix_fall_events_owner_user_id'), 'fall_events', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_fall_events_resident_id'), 'fall_events', ['resident_id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('sms', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('push', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ars', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ntfy_server', sa.Text(), nullable=True),
    sa.Column('ntfy_topic', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("role IN ('FAMILY','CAREGIVER','ADMIN')", name=op.f('ck_recipients_role')),
    sa.CheckConstraint('(facility_id IS NOT NULL) <> (owner_user_id IS NOT NULL)', name=op.f('ck_recipients_scope_xor')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_recipients_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_recipients_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], name=op.f('fk_recipients_resident_id_residents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipients'))
    )
    op.create_index(op.f('ix_recipients_facility_id'), 'recipients', ['facility_id'], unique=False)
    op.create_index(op.f('ix_recipients_owner_user_id'), 'recipients', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_recipients_resident_id'), 'recipients', ['resident_id'], unique=False)
    op.create_table('resident_devices',
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_resident_devices_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], name=op.f('fk_resident_devices_resident_id_residents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resident_id', 'device_id', name=op.f('pk_resident_devices'))
    )
    op.create_index(op.f('ix_resident_devices_device_id'), 'resident_devices', ['device_id'], unique=False)
    op.create_index('ux_resident_devices_primary', 'resident_devices', ['resident_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('event_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('fall_event_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("level IN ('INFO','WARN','ERROR','FALL')", name=op.f('ck_event_logs_level')),
    sa.CheckConstraint('(facility_id IS NOT NULL) <> (owner_user_id IS NOT NULL)', name=op.f('ck_event_logs_scope_xor')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_event_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_event_logs_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_event_logs_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fall_event_id'], ['fall_events.id'], name=op.f('fk_event_logs_fall_event_id_fall_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_event_logs_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], name=op.f('fk_event_logs_resident_id_residents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_logs'))
    )
    op.create_index(op.f('ix_event_logs_facility_id'), 'event_logs', ['facility_id'], unique=False)
    op.create_index('ix_event_logs_facility_ts', 'event_logs', ['facility_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_event_logs_owner_ts', 'event_logs', ['owner_user_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index(op.f('ix_event_logs_owner_user_id'), 'event_logs', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_owner_user_id'), table_name='event_logs')
    op.drop_index('ix_event_logs_owner_ts', table_name='event_logs')
    op.drop_index('ix_event_logs_facility_ts', table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_facility_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('ux_resident_devices_primary', table_name='resident_devices', postgresql_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_resident_devices_device_id'), table_name='resident_devices')
    op.drop_table('resident_devices')
    op.drop_index(op.f('ix_recipients_resident_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_owner_user_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_facility_id'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_fall_events_resident_id'), table_name='fall_events')
    op.drop_index(op.f('ix_fall_events_owner_user_id'), table_name='fall_events')
    op.drop_index('ix_fall_events_owner_ts', table_name='fall_events')
    op.drop_index('ix_fall_events_facility_ts', table_name='fall_events')
    op.drop_index(op.f('ix_fall_events_facility_id'), table_name='fall_events')
    op.drop_table('fall_events')
    op.drop_table('tenant_configs')
    op.drop_index(op.f('ix_residents_owner_user_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_facility_id'), table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ux_devices_scope_topic', table_name='devices', postgresql_where=sa.text('mqtt_topic IS NOT NULL'))
    op.drop_index(op.f('ix_devices_owner_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_facility_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_constraint('fk_facilities_root_user_id_users', 'facilities', type_='foreignkey')
    op.drop_index('ux_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_index('presence_samples_device_ts', table_name='presence_samples')
    op.drop_table('presence_samples')
    op.drop_table('facilities')
    # ### end Alembic commands ###
