idf_component_register(
    SRCS
        "main.c"
        "wg_spi_trace.c"
    INCLUDE_DIRS
        "."
        ".."
    REQUIRES
        esp_csi_gain_ctrl
        esp_driver_gpio
        esp_driver_spi
        esp_event
        esp_hw_support
        esp_netif
        esp_rom
        esp_wifi
        lwip
        nvs_flash
        esp_timer
)
